apiVersion: apps/v1
kind: Deployment
metadata:
  name: egovframe-web
  labels:
    app: egovframe-web
spec:
  selector:
    matchLabels:
      app: egovframe-web
  template:
    metadata:
      labels:
        app: egovframe-web
    spec:
      containers:
        - name: egovframe-web
          image: egovframe-web:5.0.0
          ports:
            - containerPort: 8080
